# Generated by Django 6.1 on 2026-09-22 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOAuthConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(db_index=True, max_length=255)),
                ('platform', models.CharField(max_length=50)),
                ('nonce', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'pending_oauth_connections',
            },
        ),
        migrations.CreateModel(
            name='BusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_id', models.CharField(db_index=True, max_length=255)),
                ('zernio_account_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('platform', models.CharField(db_index=True, max_length=50)),
                ('account_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'business_accounts',
                'indexes': [models.Index(fields=['organization_id', 'platform'], name='business_ac_organiz_53ed4e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zernio_conversation_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('zernio_account_id', models.CharField(db_index=True, max_length=255)),
                ('platform', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('participant_name', models.CharField(blank=True, max_length=255, null=True)),
                ('participant_avatar', models.TextField(blank=True, null=True)),
                ('applicant_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('contact_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('business_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='message.businessaccount')),
            ],
            options={
                'db_table': 'conversations',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zernio_message_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], db_index=True, max_length=10)),
                ('external_sender_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='message.conversation')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('FILE', 'File')], default='FILE', max_length=10)),
                ('url', models.TextField()),
                ('stored_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='message.message')),
            ],
            options={
                'db_table': 'message_attachments',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zernio_post_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('mentions', models.JSONField(blank=True, default=list)),
                ('media_urls', models.JSONField(blank=True, default=list)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(db_index=True, default='draft', max_length=50)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('platform_post_urls', models.JSONField(blank=True, default=list)),
                ('organization_id', models.CharField(db_index=True, max_length=255)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['business_account', 'updated_at'], name='conversatio_busines_0eaeda_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'direction', 'is_read'], name='messages_convers_ea7a51_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='messages_convers_3ebb41_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['organization_id', 'status'], name='posts_organiz_aa6591_idx'),
        ),
    ]
