# Generated by Django 6.1 on 2026-09-24 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
        ('user_account', '0006_user_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='businessaccount',
            name='business_ac_organiz_53ed4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_organiz_aa6591_idx',
        ),
        migrations.RemoveField(
            model_name='pendingoauthconnection',
            name='org_id',
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_accounts', to='user_account.branch'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='user_account.branch'),
        ),
        migrations.AddField(
            model_name='pendingoauthconnection',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_oauth_connections', to='user_account.branch'),
        ),
        migrations.AddField(
            model_name='post',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='user_account.branch'),
        ),
        migrations.AddIndex(
            model_name='businessaccount',
            index=models.Index(fields=['branch', 'platform'], name='business_ac_branch__7f787b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['branch', 'updated_at'], name='conversatio_branch__3f5d04_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['branch', 'status'], name='posts_branch__34029b_idx'),
        ),
        migrations.RemoveField(
            model_name='businessaccount',
            name='organization_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='organization_id',
        ),
    ]
