# Generated by Django 6.1 on 2026-09-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_per_km', models.DecimalField(decimal_places=2, default=50.0, help_text='Delivery charge per kilometer based on road distance.', max_digits=10)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=50.0, help_text='Base/minimum delivery fee applied regardless of distance.', max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this delivery pricing configuration is active.')),
            ],
            options={
                'verbose_name': 'Delivery Pricing',
                'verbose_name_plural': 'Delivery Pricings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'created_at'], name='delivery_de_is_acti_0c98f0_idx')],
            },
        ),
    ]
