# Generated by Django 6.1 on 2026-09-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverypricing',
            options={'verbose_name': 'Delivery Pricing', 'verbose_name_plural': 'Delivery Pricing'},
        ),
        migrations.RemoveIndex(
            model_name='deliverypricing',
            name='delivery_de_is_acti_0c98f0_idx',
        ),
        migrations.AlterField(
            model_name='deliverypricing',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether delivery calculation is active.'),
        ),
    ]
