# Generated by Django 6.1 on 2026-08-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_branch_alter_user_role_user_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="closing_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="branch",
            name="opening_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
