# Generated by Django 6.1 on 2026-08-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_branch_closing_time_alter_branch_opening_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
