# Generated by Django 6.1 on 2026-08-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_branch_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('reception', 'Reception'), ('rider', 'Rider'), ('kitchen', 'Kitchen'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
