# Generated by Django 6.1 on 2026-09-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='maximum_delivery_distance_km',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
        ),
    ]
