# Generated by Django 6.1 on 2026-09-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0007_branch_maximum_delivery_distance_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('reception', 'Reception'), ('rider', 'Rider'), ('kitchen', 'Kitchen'), ('customer', 'Customer'), ('staff', 'Staff')], default='customer', max_length=10),
        ),
    ]
