# Generated by Django 6.1 on 2026-08-23 07:55

import django.db.models.deletion
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_subcategory_product_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='category/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='prepare_time',
            field=models.CharField(blank=True, help_text='in minutes', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('VEG', 'Veg'), ('NON_VEG', 'Non-Veg'), ('EGG', 'Egg')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='subcategory/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail_image',
            field=models.FileField(upload_to=product.models.product_thumbnail_upload_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(upload_to=product.models.product_image_upload_path),
        ),
        migrations.CreateModel(
            name='ProductExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('additional_price', models.FloatField(default=0.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='product.product')),
            ],
            options={
                'ordering': ['additional_price', 'name'],
            },
        ),
    ]
