# Generated by Django 6.1 on 2026-08-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_meta_description_product_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('VEG', 'Veg'), ('NON_VEG', 'Non-Veg')], db_index=True, max_length=20, null=True),
        ),
    ]
