# Generated by Django 6.1 on 2026-09-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.FloatField(default=0.0),
        ),
    ]
