# Generated by Django 6.1 on 2026-09-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('VEG', 'Veg'), ('NON_VEG', 'Non-Veg'), ('DRINK', 'Drink')], db_index=True, max_length=20, null=True),
        ),
    ]
