# Generated by Django 6.1 on 2026-09-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_543da6_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_8ddc07_idx',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'is_read'], name='notificatio_notific_8a71db_idx'),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
