# Generated by Django 6.1 on 2026-08-18 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_subcategory_product_sub_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('banner_image', models.FileField(blank=True, null=True, upload_to='offers/banners/')),
                ('offer_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Discount'), ('FLAT', 'Flat Amount Discount'), ('BUY_X_GET_Y', 'Buy X Get Y (BOGO)'), ('FREE_DELIVERY', 'Free Delivery'), ('COMBO', 'Combo Deal')], db_index=True, max_length=30)),
                ('scope', models.CharField(choices=[('CART', 'Entire Cart / Order'), ('CATEGORY', 'Specific Category'), ('SUBCATEGORY', 'Specific Subcategory'), ('PRODUCT', 'Specific Product(s)')], db_index=True, default='CART', max_length=30)),
                ('discount_percentage', models.FloatField(default=0.0, help_text='Used when offer_type is PERCENTAGE')),
                ('discount_amount', models.FloatField(default=0.0, help_text='Used when offer_type is FLAT')),
                ('max_discount_amount', models.FloatField(blank=True, help_text='Cap maximum discount amount for percentage offers', null=True)),
                ('buy_quantity', models.PositiveIntegerField(default=1)),
                ('get_quantity', models.PositiveIntegerField(default=1)),
                ('get_discount_percentage', models.FloatField(default=100.0, help_text='100% means free item, 50% means half price')),
                ('min_order_amount', models.FloatField(default=0.0, help_text='Minimum order total required to apply offer')),
                ('min_item_quantity', models.PositiveIntegerField(default=1, help_text='Minimum quantity of targeted item in cart')),
                ('max_total_usage', models.PositiveIntegerField(blank=True, help_text='Total overall uses available for auto-applied offer', null=True)),
                ('max_usage_per_user', models.PositiveIntegerField(default=1, help_text='Max times a single user can redeem auto-applied offer')),
                ('current_usage_count', models.PositiveIntegerField(default=0)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, help_text='Happy hour start time (e.g. 12:00:00)', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Happy hour end time (e.g. 15:00:00)', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('buy_product', models.ForeignKey(blank=True, help_text='Required product to buy for Buy X Get Y', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buy_x_offers', to='product.product')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='product.category')),
                ('get_product', models.ForeignKey(blank=True, help_text='Product given as reward/discounted item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_y_offers', to='product.product')),
                ('products', models.ManyToManyField(blank=True, help_text='Products targeted by this offer.', related_name='offers', to='product.product')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='product.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_total_usage', models.PositiveIntegerField(blank=True, help_text='Maximum times this promo code can be used in total', null=True)),
                ('max_usage_per_user', models.PositiveIntegerField(default=1, help_text='Maximum times a single user can use this promo code')),
                ('current_usage_count', models.PositiveIntegerField(default=0)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('offer', models.ForeignKey(help_text='The offer linked to this promo code.', on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='offer.offer')),
            ],
        ),
        migrations.CreateModel(
            name='OfferRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('discount_applied', models.FloatField(default=0.0)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='offer.offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_redemptions', to=settings.AUTH_USER_MODEL)),
                ('promo_code', models.ForeignKey(blank=True, help_text='The specific promo code redeemed, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='offer.promocode')),
            ],
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['is_active', 'start_datetime', 'end_datetime'], name='offer_offer_is_acti_2c4f65_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['offer_type', 'scope', 'is_active'], name='offer_offer_offer_t_0a0ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['code', 'is_active'], name='offer_promo_code_444992_idx'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['is_active', 'start_datetime', 'end_datetime'], name='offer_promo_is_acti_72ec79_idx'),
        ),
        migrations.AddIndex(
            model_name='offerredemption',
            index=models.Index(fields=['offer', 'user'], name='offer_offer_offer_i_d80ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='offerredemption',
            index=models.Index(fields=['promo_code', 'user'], name='offer_offer_promo_c_3e1e00_idx'),
        ),
    ]
