# Generated by Django 6.1 on 2026-08-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
