# Generated by Django 6.1 on 2026-08-25 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_offer_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='offer',
        ),
        migrations.AddField(
            model_name='promocode',
            name='amount',
            field=models.FloatField(default=0.0, help_text='Discount value: amount in Rs. for AMOUNT type, or percentage rate (0-100) for PERCENTAGE type.'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='promo_type',
            field=models.CharField(choices=[('AMOUNT', 'Fixed Amount Discount'), ('PERCENTAGE', 'Percentage Discount')], db_index=True, default='AMOUNT', max_length=20),
        ),
        migrations.AlterField(
            model_name='offerredemption',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='offer.offer'),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['promo_type', 'is_active'], name='offer_promo_promo_t_142f87_idx'),
        ),
    ]
