# Generated by Django 6.1 on 2026-09-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_remove_promocode_offer_promocode_amount_and_more'),
        ('product', '0006_alter_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categories targeted by this promo code.', related_name='promo_codes', to='product.category'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='max_discount_amount',
            field=models.FloatField(blank=True, help_text='Cap maximum discount amount for percentage offers', null=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='min_order_amount',
            field=models.FloatField(default=0.0, help_text='Minimum order total required to apply this promo code.'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Products targeted by this promo code.', related_name='promo_codes', to='product.product'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='scope',
            field=models.CharField(choices=[('CART', 'Entire Cart / Order'), ('CATEGORY', 'Specific Category/Categories'), ('PRODUCT', 'Specific Product(s)')], db_index=True, default='CART', max_length=30),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='amount',
            field=models.FloatField(default=0.0, help_text='Discount value: amount in Rs. for AMOUNT / DELIVERY_CHARGE type, or percentage rate (0-100) for PERCENTAGE type.'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='promo_type',
            field=models.CharField(choices=[('AMOUNT', 'Fixed Amount Discount'), ('PERCENTAGE', 'Percentage Discount'), ('DELIVERY_CHARGE', 'Delivery Charge Discount / Free Delivery')], db_index=True, default='AMOUNT', max_length=30),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(fields=['scope', 'is_active'], name='offer_promo_scope_948ec1_idx'),
        ),
    ]
