# Generated by Django 6.1 on 2026-09-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_promocode_categories_promocode_max_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='max_usage_per_user',
        ),
    ]
