# Generated by Django 6.1 on 2026-08-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_meta_description_blog_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
