from django.contrib.auth import authenticate, get_user_model
from rest_framework import serializers

from account.models import Branch
from account.services.auth_service import register_user

User = get_user_model()


class UserSerializer(serializers.ModelSerializer):
    """
    Serializer representing the User profile details.
    """

    full_name = serializers.SerializerMethodField()

    class Meta:
        model = User
        fields = (
            "id",
            "username",
            "email",
            "first_name",
            "last_name",
            "full_name",
            "phone_number",
            "role",
            "branch",
        )
        read_only_fields = ("id",)

    def get_full_name(self, obj):
        name = f"{obj.first_name} {obj.last_name}".strip()
        return name if name else obj.username


class UserUpdateSerializer(serializers.ModelSerializer):
    """
    Serializer for updating user details (first_name, last_name, email, phone_number, role, branch).
    """

    full_name = serializers.SerializerMethodField()

    class Meta:
        model = User
        fields = (
            "id",
            "username",
            "email",
            "first_name",
            "last_name",
            "full_name",
            "phone_number",
            "role",
            "branch",
        )
        read_only_fields = ("id",)

    def get_full_name(self, obj):
        name = f"{obj.first_name} {obj.last_name}".strip()
        return name if name else obj.username

    def validate_email(self, value):
        if value:
            user_id = self.instance.id if self.instance else None
            if User.objects.filter(email__iexact=value).exclude(id=user_id).exists():
                raise serializers.ValidationError(
                    "A user with this email address already exists."
                )
        return value

    def validate_phone_number(self, value):
        if value:
            user_id = self.instance.id if self.instance else None
            if User.objects.filter(phone_number=value).exclude(id=user_id).exists():
                raise serializers.ValidationError(
                    "A user with this phone number already exists."
                )
        return value



class SignupSerializer(serializers.Serializer):
    """
    Serializer for handling user registration with full_name, email, password, and optional phone_number.
    """

    full_name = serializers.CharField(max_length=255, required=True)
    email = serializers.EmailField(required=True)
    password = serializers.CharField(write_only=True, required=True, min_length=6)
    phone_number = serializers.CharField(
        max_length=20, required=False, allow_blank=True, default=""
    )
    role = serializers.ChoiceField(
        choices=User.ROLE_CHOICES, required=False, default="customer"
    )
    branch = serializers.PrimaryKeyRelatedField(
        queryset=Branch.objects.all(), required=False, allow_null=True, default=None
    )

    def validate_email(self, value):
        if value:
            if User.objects.filter(email__iexact=value).exists():
                raise serializers.ValidationError(
                    "A user with this email address already exists."
                )
        return value

    def create(self, validated_data):
        return register_user(
            full_name=validated_data["full_name"],
            email=validated_data["email"],
            password=validated_data["password"],
            phone_number=validated_data.get("phone_number", ""),
            role=validated_data.get("role", "customer"),
            branch=validated_data.get("branch"),
        )


class LoginSerializer(serializers.Serializer):
    """
    Serializer for validating user login credentials using email and password.
    """

    email = serializers.EmailField(required=True)
    password = serializers.CharField(write_only=True, required=True)

    def validate(self, attrs):
        email = attrs.get("email")
        password = attrs.get("password")

        user_obj = User.objects.filter(email__iexact=email).first()

        if not user_obj:
            raise serializers.ValidationError(
                "Unable to log in with provided credentials. Invalid email or password."
            )

        user = authenticate(username=user_obj.username, password=password)

        if not user:
            raise serializers.ValidationError(
                "Unable to log in with provided credentials. Invalid email or password."
            )

        if not user.is_active:
            raise serializers.ValidationError("User account is deactivated.")

        attrs["user"] = user
        return attrs


class GoogleLoginSerializer(serializers.Serializer):
    """
    Serializer for validating Google OAuth social login payload.
    """

    id_token = serializers.CharField(
        required=False,
        allow_blank=True,
        help_text="Google OAuth2 ID token generated by frontend/client login.",
    )
    access_token = serializers.CharField(
        required=False,
        allow_blank=True,
        help_text="Google OAuth2 Access token generated by frontend/client login.",
    )
    client_id = serializers.CharField(
        required=False,
        allow_blank=True,
        help_text="Optional Google OAuth Client ID.",
    )

    def validate(self, attrs):
        id_token = attrs.get("id_token")
        access_token = attrs.get("access_token")

        if not id_token and not access_token:
            raise serializers.ValidationError(
                "At least one of 'id_token' or 'access_token' is required."
            )
        return attrs


class CustomerCreateSerializer(serializers.Serializer):
    """
    Serializer for creating a customer using only full_name and phone_number.
    Does not require email or password.
    """

    full_name = serializers.CharField(max_length=255, required=True)
    phone_number = serializers.CharField(max_length=20, required=True)

    def validate_phone_number(self, value):
        if value:
            if User.objects.filter(phone_number=value).exists():
                raise serializers.ValidationError(
                    "A customer with this phone number already exists."
                )
        return value

    def create(self, validated_data):
        full_name = validated_data["full_name"]
        phone_number = validated_data["phone_number"]

        names = full_name.strip().split(" ", 1)
        first_name = names[0]
        last_name = names[1] if len(names) > 1 else ""

        # Generate a unique username from phone number or name
        base_username = phone_number if phone_number else f"cust_{first_name.lower()}"
        username = base_username
        counter = 1
        while User.objects.filter(username__iexact=username).exists():
            username = f"{base_username}_{counter}"
            counter += 1

        user = User(
            username=username,
            first_name=first_name,
            last_name=last_name,
            phone_number=phone_number,
            role="customer",
        )
        user.set_unusable_password()
        user.save()
        return user


class BranchSerializer(serializers.ModelSerializer):

    """
    Serializer representing the Branch details.
    """

    class Meta:
        model = Branch
        fields = (
            "id",
            "name",
            "slug",
            "address",
            "latitude",
            "longitude",
            "phone",
            "image",
            "opening_time",
            "closing_time",
            "created_at",
            "updated_at",
        )
        read_only_fields = ("id", "slug", "created_at", "updated_at")

