# Generated by Django 6.1 on 2026-09-09 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('heading', models.FloatField(default=0.0, help_text='Compass direction in degrees (0.0 to 360.0)')),
                ('is_online', models.BooleanField(db_index=True, default=True, help_text='Designates whether the rider is currently active and available.')),
                ('last_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider Location',
                'verbose_name_plural': 'Rider Locations',
                'db_table': 'tracking_rider_location',
                'indexes': [models.Index(fields=['is_online', 'last_updated_at'], name='tracking_ri_is_onli_d82ccc_idx'), models.Index(fields=['latitude', 'longitude'], name='tracking_ri_latitud_eb9fc5_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiderLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('heading', models.FloatField(default=0.0)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rider Location History',
                'verbose_name_plural': 'Rider Location Histories',
                'db_table': 'tracking_rider_location_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rider', 'created_at'], name='tracking_ri_rider_i_3abff0_idx')],
            },
        ),
    ]
