# Generated by Django 6.1 on 2026-09-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderlocation',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='riderlocationhistory',
            name='heading',
        ),
    ]
