# Generated by Django 6.1 on 2026-08-23 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0004_category_image_product_is_best_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, help_text='Human-readable order ID, e.g. EAT_482931', max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='extras_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='OrderItemExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_name', models.CharField(max_length=100)),
                ('additional_price', models.FloatField(default=0.0)),
                ('extra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_extras', to='product.productextra')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_extras', to='order.orderitem')),
            ],
            options={
                'indexes': [models.Index(fields=['order_item'], name='order_order_order_i_8ec1dc_idx')],
            },
        ),
    ]
