# Generated by Django 6.1 on 2026-08-23 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_branch_slug'),
        ('order', '0002_order_order_number_orderitem_extras_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Nearest branch assigned to fulfill this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='user_account.branch'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
