# Generated by Django 6.1 on 2026-09-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_assigned_to_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='barcode_number',
            field=models.CharField(blank=True, db_index=True, help_text='Unique barcode number for scanning, e.g. 890123456789', max_length=20, null=True, unique=True),
        ),
    ]
