# Generated by Django 6.1 on 2026-09-02 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_remove_promocode_offer_promocode_amount_and_more'),
        ('order', '0006_order_barcode_number'),
        ('user_account', '0006_user_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('NPS', 'NPS Payment')], db_index=True, default='COD', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_type', 'is_paid'], name='order_order_payment_7e6b9f_idx'),
        ),
    ]
