# Generated by Django 6.1 on 2026-09-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('DELIVERY', 'Delivery'), ('TAKEAWAY', 'Takeaway'), ('POS', 'POS'), ('DINEIN', 'Dine in')], db_index=True, max_length=20, null=True),
        ),
    ]
