# Generated by Django 6.1 on 2026-09-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('DELIVERY', 'Delivery'), ('TAKEAWAY', 'Takeaway'), ('DINEIN', 'Dine in')], db_index=True, max_length=20, null=True),
        ),
    ]
