# Generated by Django 6.1 on 2026-09-28 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_customer_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], db_index=True, help_text='Type of action performed: CREATE, UPDATE, DELETE.', max_length=20)),
                ('entity_type', models.CharField(choices=[('ORDER', 'Order'), ('ORDER_DETAIL', 'Order Detail'), ('PRODUCT', 'Product'), ('CATEGORY', 'Category'), ('USER', 'User'), ('SETTING', 'Setting')], db_index=True, help_text='Category of the entity affected.', max_length=30)),
                ('entity_name', models.CharField(db_index=True, help_text='Target model or entity name (e.g. Order, OrderItem, Product, Category, User, DeliveryPricing).', max_length=100)),
                ('record_id', models.CharField(blank=True, db_index=True, help_text='Primary key/identifier of the affected record.', max_length=100, null=True)),
                ('record_repr', models.CharField(blank=True, help_text='Human-readable title or label of the affected record.', max_length=255, null=True)),
                ('description', models.TextField(help_text='Human-readable summary of the change or event.')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Dictionary detailing changed fields with their previous and new values.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address where the action originated.', null=True)),
                ('order', models.ForeignKey(blank=True, help_text='Associated Order if this activity relates to an order or its items.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='order.order')),
                ('user', models.ForeignKey(blank=True, help_text='User who triggered this action (if authenticated).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['entity_type', 'created_at'], name='order_activ_entity__5e152c_idx'), models.Index(fields=['action_type', 'created_at'], name='order_activ_action__37f3fc_idx'), models.Index(fields=['order', 'created_at'], name='order_activ_order_i_5fb095_idx'), models.Index(fields=['user', 'created_at'], name='order_activ_user_id_f391df_idx'), models.Index(fields=['entity_name', 'record_id'], name='order_activ_entity__6ee40f_idx')],
            },
        ),
    ]
